name: Default CI Pipeline

on: [push, pull_request]

jobs:
  setup-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      
      - name: Use lerna
        run: npm install -g lerna
      
      - name: Bootstrap
        run: lerna bootstrap --no-ci
      
      - name: Test
        run: lerna run test --no-bail --stream
        env:
          # avoid errors from gist_backend test
          TD_PLAYGROUND_LOGIN: example
          TD_PLAYGROUND_TOKEN: example