name: Deploy Pipeline

on: [push]

jobs:
  remote-ssh-script:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sshTest
        run: ./.github/scripts/deploy-web.sh
        shell: bash
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
          SSH_HOST: ${{ secrets.SSH_HOST }}