name: Deploy Pipeline

on: [push]

jobs:
  my-test:

    runs-on: ubuntu-latest

    steps:
      - name: sshTest
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls
        host: bandit.labs.overthewire.org
        user: bandit0
        port: 2220
        key: bandit0