name: Deploy Pipeline

on: [push]

jobs:
  my-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sshTest
        run: ./.github/scripts/deploy-web.sh
        shell: bash
        env:
          PG_TEST: ${{ secrets.PG_TEST }}
          MY_HOST: ${{ secrets.MY_HOST }}